# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# qb machine Vagrant Box.
#

Vagrant.configure(2) do |config|
    # Set the VM name.
    config.vm.provider :virtualbox do |vb|
        vb.name = "qb-machine"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    
    # Message to display after boot.
    config.vm.post_up_message = "Wooo! We're in a qb machine!"
    
    # Set the VM hostname.
    config.vm.hostname = "qb-machine"
    
    # Use a very minimal Ubuntu Xenial box.
    config.vm.box = "geerlingguy/ubuntu1604"

    # Bind the LXD REST API to localhost.
    config.vm.network "forwarded_port", guest: 8443, host: 9443

    config.vm.provision "shell", inline: <<-SHELL
        export DEBIAN_FRONTEND=noninteractive

        # Install LXD.
        sudo apt-get update
        sudo apt-get -y install lxd

        # Allow LXD API over TCP.
        sudo lxc config set core.https_address "[::]:8443"

        # Trust localhost's LXD API cert.
        sudo lxc config trust add /vagrant/lxd/client.crt
  SHELL
end
